version: '3.8'
services:
  logstash:
    image: jamesgarside/logstash:7.10.0
    environment:
      NODE_NAME: logstash
    networks:
      - elastic
    ports: 
      - "9600:9600"
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - node.name=es01
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elastic
volumes:
  data01:
networks:
  elastic:
    driver: overlay